<a href="https://colab.research.google.com/github/WhiteWolf088/Numpy/blob/main/Basics_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

## Single Dimensional Array

In [1]:
# Importing numpy Library
import numpy as np

In [2]:
A=np.array([1,4,5,3,2])   #Single Dimensional Array
A

array([1, 4, 5, 3, 2])

In [3]:
A.shape

(5,)

In [4]:
A.size

5

In [5]:
A.ndim # Number of Dimensions

1

In [6]:
type(A)

numpy.ndarray

In [7]:
A.dtype

dtype('int64')

In [8]:
np.sort(A) # Faster to give the Output

array([1, 2, 3, 4, 5])

In [9]:
A.sort()
A

array([1, 2, 3, 4, 5])

In [10]:
np.min(A)

1

In [11]:
np.max(A)

5

In [12]:
np.sum(A)

15

In [13]:
np.mean(A)

3.0

In [14]:
np.median(A)

3.0

In [15]:
np.sin(A)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [16]:
np.cos(A)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [17]:
np.tan(A)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [18]:
np.power(A,3)

array([  1,   8,  27,  64, 125])

In [19]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [20]:
B=np.array(['aaa','bbb','ccc','ddd'])
B

array(['aaa', 'bbb', 'ccc', 'ddd'], dtype='<U3')

In [21]:
type(B)

numpy.ndarray

In [22]:
B.dtype  # "U" Stands for 'Unicode' and "3" stands for number of elements in a string

dtype('<U3')

In [23]:
x=np.array([1,4,7,2,5])
y=np.array([8,3,6,9,10])
x,y   # You can also perform Arithmetic Operations

(array([1, 4, 7, 2, 5]), array([ 8,  3,  6,  9, 10]))

In [24]:
x+y

array([ 9,  7, 13, 11, 15])

In [25]:
x-y

array([-7,  1,  1, -7, -5])

In [26]:
x*y

array([ 8, 12, 42, 18, 50])

In [27]:
x/y # Quotient

array([0.125     , 1.33333333, 1.16666667, 0.22222222, 0.5       ])

In [28]:
x//y # Perfect Division

array([0, 1, 1, 0, 0])

In [29]:
x%y # remainder

array([1, 1, 1, 2, 5])

In [30]:
x**y # Power

array([      1,      64,  117649,     512, 9765625])

In [31]:
np.sin(x) # Trignometry Functions

array([ 0.84147098, -0.7568025 ,  0.6569866 ,  0.90929743, -0.95892427])

In [32]:
np.power(x,5)

array([    1,  1024, 16807,    32,  3125])

In [33]:
np.sqrt(x)

array([1.        , 2.        , 2.64575131, 1.41421356, 2.23606798])

## Multi Dimensional Array

* All the above Built-in functions are also works for Multi Dimensional Array

In [34]:
C=np.array([[1,2,3,4,5],[6,7,8,9,10]])  # Multidimensional Array
C

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### Ones

In [35]:
D=np.ones(5)
D

array([1., 1., 1., 1., 1.])

In [36]:
# By default np.ones are Float but You can change the Data type by Using dtype function

In [37]:
D=np.ones(5,dtype='int32')
D

array([1, 1, 1, 1, 1], dtype=int32)

In [38]:
E=np.ones([5,5]) #matrix by using np.ones()  # It is Used as a white background (in image processing)
E

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
# Same as above You can change data type

In [40]:
E=np.ones([5,5],dtype='int32')
E

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

### Zeros

In [41]:
F=np.zeros(5)
F

array([0., 0., 0., 0., 0.])

In [42]:
# By default np.zeros also in float

In [43]:
F=np.zeros(5,dtype='int32')
F

array([0, 0, 0, 0, 0], dtype=int32)

In [44]:
G=np.zeros([5,5])  #matrix by using np.zeros()  # It is Used as a Black background (in image processing)
G

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
# Same as above You can change data type

In [46]:
G=np.zeros([5,5],dtype='int32')
G

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

* Some Other Functions With Numpy

In [47]:
# Range of array Values
H=np.arange(5)
H

array([0, 1, 2, 3, 4])

In [48]:
np.arange(2,10) # 10 is exclusive

array([2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.linspace(1,10,5) # Return evenly spaced numbers over a specified interval.

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [50]:
np.linspace(1,2,15) # It divides 15 equal parts from 1 to 2

array([1.        , 1.07142857, 1.14285714, 1.21428571, 1.28571429,
       1.35714286, 1.42857143, 1.5       , 1.57142857, 1.64285714,
       1.71428571, 1.78571429, 1.85714286, 1.92857143, 2.        ])

In [51]:
# Numpy can create a random integers by using Random Function 
#Return random integers from `low` (inclusive) to `high` (exclusive)
np.random.randint(1,100,20)  # Here 20 is number of random element we want from 1 to 2

array([85, 25, 86, 82, 25, 19, 63, 48,  6,  3,  6, 81, 30, 42, 65, 53, 79,
       50, 79, 90])